### ISSUE TITLE
font

### ISSUE THREAD

**Issue by willin** [js-org/logo#1]
hi there,

what tool do you use to build webfont like this?

**Comment by indus** [comment]
https://icomoon.io/ (and Adobe Illustrator in the beginning) but there are others.

**Comment by willin** [comment]
<img width="619" alt="qq20170317-1 2x" src="https://cloud.githubusercontent.com/assets/1890238/24026986/91f3064a-0aff-11e7-94ff-f4fc70a2e476.png">

<img width="584" alt="qq20170317-1 2x" src="https://cloud.githubusercontent.com/assets/1890238/24027003/a1316f48-0aff-11e7-86af-5f3b6965ac91.png">

@indus  where did i do wrong?

**Comment by indus** [comment]
I don't give support for this tool. Ask the creator
